// import 'package:flutter/widgets.dart';

import 'package:flutter/material.dart';
import 'package:invoicediscounting/src/components/faq_card.dart';
import 'package:invoicediscounting/src/constant/app_color.dart';

class ReturnTaxation extends StatelessWidget {
  const ReturnTaxation({super.key});

  @override
  Widget build(BuildContext context) {
    final bool isTablet = MediaQuery.of(context).size.width >= 600;

    return Scaffold(
      backgroundColor: backgroundColor,
      appBar: AppBar(
        centerTitle: true,
        elevation: 0,
        title: Text("Return Taxation", style: Theme.of(context).textTheme.headlineMedium),
        backgroundColor: backgroundColor,
        iconTheme: IconThemeData(color: blackColor),
      ),
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: isTablet ? 120 : 16),
        child: Column(
          children: const [
            FAQCard(
              question: "Does Birbal Plus guarantee any return on investment?",
              answer:
                  "Birbal Plus does not guarantee any returns on investments made through the platform. Investors are advised to invest at their sole discretion. Please read this disclaimer before you invest",
            ),
            FAQCard(
              question: "How are my returns taxed?",
              answer:
                  "Returns earned are taxed as per applicable Income Tax laws based on your tax slab. Tax Deducted at Source (TDS) may apply wherever mandated.",
            ),
            FAQCard(
              question: "What is Extended Internal Rate of Return (XIRR)?",
              answer:
                  "XIRR is the annualized rate of return that considers the exact dates of your investments and payouts, giving a more accurate return calculation.",
            ),
            FAQCard(
              question: "What is Internal Rate of Return (IRR)",
              answer:
                  "IRR is the expected annual return generated by an investment based on projected cash flows over its tenure.",
            ),
            // FAQCard(
            //   question: "What is extended Internal Rate of Return (XIRR)?",
            //   answer:
            //       "XIRR measures the actual return considering the timing of each cash flow.",
            // ),
          ],
        ),
      ),
    );
  }
}
